services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - prestashop_network
    depends_on:
      - mysql
    ports:
      - 8081:80
    links:
      - mysql:db
    environment:
      - PMA_HOST=some-mysql
      - PMA_USER=root
      - PMA_PASSWORD=admin
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL: install4577
      PS_INSTALL_AUTO: 0
      PS_DOMAIN: localhost:8080
      PS_DEV_MODE: 1
      PS_LANGUAGE: it
      ADMIN_MAIL: agiaquinto87@gmail.com
      ADMIN_PASSWD: ciao
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=yes"
      PHP_IDE_CONFIG: "serverName=prestashop"
    extra_hosts:  # correzione: era 'extra_host'
      - "host.docker.internal:host-gateway"
    networks:
      - prestashop_network
    volumes:
#      - type: bind
#        source: ./modules/carforagest # local path to the module
#        target: /var/www/html/modules/carforagest # path to be mounted in the container
#      - type: bind
#        source: ./modules/carforastore # local path to the module
#        target: /var/www/html/modules/carforastore # path to be mounted in the container
#      - type: bind
#        source: ./themes/carforaclick
#        target: /var/www/html/themes/carforaclick
      - type: bind
        source: ./carforaclick_docker
        target: /var/www/html
      - type: bind
        source: ./xdebug.ini
        target: /usr/local/etc/php/conf.d/xdebug.ini
#      - psdata:/var/www/html
networks:
  prestashop_network:
volumes:
#  psdata:
  dbdata:
